import matplotlib.pyplot as plt
import numpy as np

if __name__ == "__main__":

    show_plots = False
    dat = np.load('corrcostvar.npz')

    # Plot correlations and costs
    fig, ax = plt.subplots()
    ax.plot(dat['ss'][0], dat['rho12s'], color='blue', label='rho12')
    ax.plot(dat['ss'][0], dat['rho13s'], color='orange', label='rho13')
    ax.scatter(dat['pp'][0], dat['fom_rom_corrs'], color='orange', label='FOM-ROM Corrs')
    ax.plot(dat['ss'][0], dat['rho23s'], color='green', label='rho23')
    ax.scatter(dat['pp'][0], dat['aux_rom_corrs'], color='green', label='AUX-ROM Corrs')
    # ax.scatter(dat['s_star'][1], rho13(s_star), marker='*', s=200, color='grey')
    plt.axvline(round(dat['s_star'][1]), color='gray')
    ax.set_xlabel('Basis size')
    ax.set_ylabel('Correlation')
    ax.legend()
    plt.tight_layout()
    plt.savefig('correlation_plot.pdf', transparent=True)
    if show_plots: plt.show()

    fig, ax = plt.subplots()
    ax.plot(dat['ss'][0], dat['cost2s'], color='blue', label='cost2')
    ax.plot(dat['ss'][0], dat['cost3s'], color='orange', label='cost3')
    ax.scatter(dat['pp'][0], dat['normalized_rom_times'], color='orange', label='Normalized ROM Time')
    # ax.scatter(s_star[1], cost3_half(s_star[1]), marker='*', s=200, color='grey')
    plt.axvline(round(dat['s_star'][1]), color='gray')
    ax.set_xlabel('Basis size')
    ax.set_ylabel('Model Costs')
    ax.legend()
    plt.tight_layout()
    plt.savefig('cost_plot.pdf', transparent=True)
    if show_plots: plt.show()

    fig, ax = plt.subplots()
    ax.loglog(dat['xx'], 1/dat['xx'], color='black', label='MC')
    # plt.loglog(xx, 1/xx * np.array(funcMFs), linestyle=':', color='blue', label='ACV-MF Prediction')
    # plt.loglog(xx, 1/xx * np.array(funcMFs_exact), color='blue', label='ACV-MF Actual')
    # plt.loglog(xx, 1/xx * np.array(funcISs), linestyle=':', color='orange', label='ACV-IS Predicted')
    # plt.loglog(xx, 1/xx * np.array(funcISs_exact), color='orange', label='ACV-IS Actual')
    # plt.loglog(xx, np.exp(np.array(funcMFs)), linestyle=':', color='blue', label='ACV-MF Prediction')
    # plt.loglog(xx, np.exp(np.array(funcMFs_exact)), color='blue', label='ACV-MF Actual')
    # plt.loglog(xx, np.exp(np.array(funcISs)), linestyle=':', color='orange', label='ACV-IS Predicted')
    # plt.loglog(xx, np.exp(np.array(funcISs_exact)), color='orange', label='ACV-IS Actual')
    ax.loglog(dat['xx'], dat['fMFs'], linestyle=':', color='blue', label='ACV-MF Prediction')
    ax.loglog(dat['xx'], dat['fMFs_ex'], color='blue', label='ACV-MF Actual')
    ax.loglog(dat['xx'], dat['fISs'], linestyle=':', color='orange', label='ACV-IS Predicted')
    ax.loglog(dat['xx'], dat['fISs_ex'], color='orange', label='ACV-IS Actual')
    # plt.loglog(xx, 1/xMFs[:,0] * np.array(funcMFs), linestyle=':', color='blue', label='ACV-MF Prediction')
    # plt.loglog(xx, 1/xMFs_exact[:,0] * np.array(funcMFs_exact), color='blue', label='ACV-MF Actual')
    # plt.loglog(xx, 1/xISs[:,0] * np.array(funcISs), linestyle=':', color='orange', label='ACV-IS Predicted')
    # plt.loglog(xx, 1/xISs_exact[:,0] * np.array(funcISs_exact), color='orange', label='ACV-IS Actual')
    # plt.xlabel('Budget')
    # plt.ylabel('Estimator Variance')
    ax.legend()
    plt.tight_layout()
    plt.savefig('variance_plot.pdf', transparent=True)
    if show_plots: plt.show()