[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "romtools"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.8"
scripts = { romtools-format = "romtools.workflows.formatting:main" }
dependencies = [
    'numpy',
    'scipy',
    'matplotlib',
]

[tool.setuptools.dynamic]
version = {file = "version.txt"}

[tool.setuptools.packages.find]
where = ["."]

#https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies
[project.optional-dependencies]
WithMPI = ['mpi4py>3.1.4']
WithH5py = ['h5py']
hpc = [
    'argparse',
    'pyyaml',
]
docs = [
    'docutils',
    'sphinx',
    'pydata-sphinx-theme',
    'sphinx-copybutton',
    'sphinx-design',
    'myst-nb>=0.18',
    'jupyter-sphinx',
]
test = [
    'pytest==7.4.4',
    'pytest-mpi>=0.6',
    'pytest-timeout',
]

[tool.pytest.ini_options]
markers = [
    "regression: regression tests with checked-in gold files",
]
