name: Check formatting

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.event.repository.name }}-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: True

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # true -> cancel all jobs if any fails
      matrix:
        python-version: ['3.8', '3.9','3.10','3.11']

    steps:
      - uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip list
          pip install .

      - name: Run Pylint
        run: |
          pylint --rcfile .pylintrc .
        continue-on-error: true

      - name: Check Pylint Exit Code
        run: |
          if [[ $? -ne 0 ]]; then
            echo "Pylint failed with a score below 8.5"
            exit 1
          fi
